# path to output directory to store result files
out_dir: /s/project/py_fraser/PROTRIDER/output_gtex/Brain
#out_dir: /s/project/py_fraser/PROTRIDER/output_kremer/fraser

# csv input file containing intensities. Columns are samples and rows are proteins.
input_intensities: "sample_data/protrider_sample_dataset.tsv"
#split_reads: "/s/project/py_fraser/exported_counts/fraser8653/raw-local-fraser_s.csv"
#unsplit_reads: "/s/project/py_fraser/exported_counts/fraser8653/raw-local-fraser_u.csv"
split_reads: "/s/project/py_fraser/PROTRIDER/sample_data/gtex/raw-local-Brain_-_Cerebellum_s.csv"
unsplit_reads: "/s/project/py_fraser/PROTRIDER/sample_data/gtex/raw-local-Brain_-_Cerebellum_u.csv"

# column name in the input file indicating the column name containing the protein names/IDs
#index_col: "protein_ID"
input_format: "introns_as_rows"

# csv file containing sample annotations
# sample_annotation: sample_data/sample_annotations.tsv

## Preprocessing params
# maximum percentage of missing values per protein
max_allowed_NAs_per_protein: 0.3
# transformation funtion to apply to the data before model fitting. options are log10, log2, and log
# set this to null if the data is already log-transformed
#log_func_name: "log"

analysis: "fraser"
fpkmCutoff: 1
# gtf: "/s/genomes/human/hg38/gencode.v34/gencode.v34.annotation.gtf.gz"
#gtf: "/s/genomes/human/hg19/gencode29/gencode.v29lift37.sorted.gtf.gz" # kremer
gtf: "/s/genomes/human/hg38/gencode.v34/gencode.v34.annotation.gtf.gz" #gtex

# names of columns in the sample annotation file to be passed as covariates to the autoencoder.
# leaving this empty results in no covariates passed to the model
cov_used:
# - SEX
# - AGE
# - "BATCH_RUN"

# seed parameter for reproducibility
seed: 42

## Grid search outlier injection params
inj_freq: 1e-3
inj_mean: 3
inj_sd: 1.6
gs_epochs: 100

## Model params
autoencoder_training: False ## when set to false, it returns values after (PCA) initialization without training
autoencoder_loss: "NLL" # MSE or NLL

n_layers: 1 # number of layers for the autoencoder model
n_epochs: 100 # number of training epochs
lr: 1e-4 # learning rate
batch_size:

find_q_method: "OHT" # option to find latent space dimension. Options: OHT, gs or an integer value
init_pca: True # PCA initialization
h_dim: # hidden dimension, only for n_layers>1

## Presence absence modelling
presence_absence: False
lambda_presence_absence: 0.5

## Cross-validation parameters
cross_val: False # run protrider in k-fold cross-validation mode; only implemented for OHT; defaults to False
#n_folds: 5 # number of folds for cross-validation; defaults to 5
#early_stopping_patience: 50 # patience for early stopping
#early_stopping_min_delta: 0.0001 # minimum difference to monitor for early stopping
#fit_every_fold: False # fit residual model for every fold; defaults to false

## Stat params
pval_dist: 'bb' # Distribution choice for P-value computation. Options: gaussian, t, nb, bb
pval_adj: 'holm' # Multiple testing correction. Options: by, bh, holm
pval_sided: 'two-sided'
pseudocount: 0.1 # for FC computation (and jaccard)
min_delta_psi: 0.05  # for fraser jaccard variability filter


## Reporting params
outlier_threshold: 0.1 # for adjusted p values 
delta_psi_threshold : 0.1 # for fraser
min_count : 5 # for fraser
report_all: False 
aggregate : False

verbose: False
device: 'cpu'

min_expression_in_one_sample: 20
quantile_min_expression : 10
quantile_for_filtering: 0.75 

n_jobs: 8

